concurrency: 3
receiver_type: rmq
rec_rmq:
  host: 'localhost'
  port: 5672
  username: 'guest'
  password: 'guest'
  queue: 'submission_queue'
publisher_type: file|rmq
pub_rmq:
  host: 'localhost'
  port: 5672
  username: 'guest'
  password: 'guest'
  queue: 'submission_queue'
pub_file:
  name: 'executor.log'